# docker-compose.override.yml
services:
  mysql_source:
    image: mysql:8.0
    container_name: mysql_source
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: sourcedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: p@ssw0rd
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3308:3308"
    networks:
      - airflow

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8081
    ports:
      - "8081:8081"
      - "7077:7077"
    volumes:
      - spark-data:/bitnami
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./jars/mysql-connector-java-8.0.28.jar:/opt/bitnami/spark/jars/mysql-connector-java-8.0.28.jar
    networks:
      - airflow

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./include:/usr/local/airflow/include
      - spark-data:/bitnami
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./jars/mysql-connector-java-8.0.28.jar:/opt/bitnami/spark/jars/mysql-connector-java-8.0.28.jar

    depends_on:
      - spark-master
    networks:
      - airflow

volumes:
  mysql-data:
  spark-data:
